// Generated by gencpp from file imu_reader/pid_control_req.msg
// DO NOT EDIT!


#ifndef IMU_READER_MESSAGE_PID_CONTROL_REQ_H
#define IMU_READER_MESSAGE_PID_CONTROL_REQ_H

#include <ros/service_traits.h>


#include <imu_reader/pid_control_reqRequest.h>
#include <imu_reader/pid_control_reqResponse.h>


namespace imu_reader
{

struct pid_control_req
{

typedef pid_control_reqRequest Request;
typedef pid_control_reqResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pid_control_req
} // namespace imu_reader


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::imu_reader::pid_control_req > {
  static const char* value()
  {
    return "e3f3937906a511b0cf091d670e4b7a78";
  }

  static const char* value(const ::imu_reader::pid_control_req&) { return value(); }
};

template<>
struct DataType< ::imu_reader::pid_control_req > {
  static const char* value()
  {
    return "imu_reader/pid_control_req";
  }

  static const char* value(const ::imu_reader::pid_control_req&) { return value(); }
};


// service_traits::MD5Sum< ::imu_reader::pid_control_reqRequest> should match 
// service_traits::MD5Sum< ::imu_reader::pid_control_req > 
template<>
struct MD5Sum< ::imu_reader::pid_control_reqRequest>
{
  static const char* value()
  {
    return MD5Sum< ::imu_reader::pid_control_req >::value();
  }
  static const char* value(const ::imu_reader::pid_control_reqRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::imu_reader::pid_control_reqRequest> should match 
// service_traits::DataType< ::imu_reader::pid_control_req > 
template<>
struct DataType< ::imu_reader::pid_control_reqRequest>
{
  static const char* value()
  {
    return DataType< ::imu_reader::pid_control_req >::value();
  }
  static const char* value(const ::imu_reader::pid_control_reqRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::imu_reader::pid_control_reqResponse> should match 
// service_traits::MD5Sum< ::imu_reader::pid_control_req > 
template<>
struct MD5Sum< ::imu_reader::pid_control_reqResponse>
{
  static const char* value()
  {
    return MD5Sum< ::imu_reader::pid_control_req >::value();
  }
  static const char* value(const ::imu_reader::pid_control_reqResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::imu_reader::pid_control_reqResponse> should match 
// service_traits::DataType< ::imu_reader::pid_control_req > 
template<>
struct DataType< ::imu_reader::pid_control_reqResponse>
{
  static const char* value()
  {
    return DataType< ::imu_reader::pid_control_req >::value();
  }
  static const char* value(const ::imu_reader::pid_control_reqResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IMU_READER_MESSAGE_PID_CONTROL_REQ_H
